--- #YAML:1.0
name:                WWW-Reddit
version:             0.04
abstract:            interface with reddit.com
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Object::InsideOut:             0
    Test::MockObject::Extends:     0
    Test::More:                    0
    WWW::Mechanize:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andrew Moore <amoore@cpan.org>
